### ISSUE TITLE
Spoiler function.

### ISSUE THREAD

**Issue by TheZennou** [kwaroran/character-card-spec-v3#1]
Pretty simple and useful, a spoiler field that warns the user that it contains spoilers, and they must confirm they want to see it. Would be good for secrets, or even putting some of the features of the V3 spec into a "hidden" field.

**Comment by kwaroran** [comment]
Do you mean something like: "Click to reveal the text"?

**Comment by TheZennou** [comment]
Exactly that. Just to make a little barrier to revealing something important.
Currently I just make an entry called "SPOILER - DO NOT OPEN" in the lorebook, but it'd be nice to have a real spoiler function.

**Comment by kwaroran** [comment]
`{{reverse:A}}` is added for the spoilers. This will not serve as a spoiler warning, but it will still help prevent spoilers.

**Comment by TheZennou** [comment]
Cool.
