### ISSUE TITLE
chara-ext-asset_ with or without colon?

### ISSUE THREAD

**Issue by DominaeDev** [kwaroran/character-card-spec-v3#8]
From the spec:
> PNG/APNG files MAY have additional tEXt chunks that works like assets embedded in CHARX files. the tEXt chunk MUST be named `chara-ext-asset_:{path}` and the value of the tEXt chunk MUST be the base64 encoded binary data. and it could be accessed by `__asset:{path}` URI. however, implementing this on new applications SHOULD be avoided, and CHARX files SHOULD be used instead.

I noticed the chunk name differs from how it's implementation in RisuAI ([see code](https://github.com/kwaroran/RisuAI/blob/7356b0426eb45ec32e2ca2de27f48f2268f8109b/src/ts/characterCards.ts#L135)). There is no colon in Risu, but there is one in the spec, but then the underscore looks a bit superfluous. So I'm left to wonder: which one is correct? Is it the RisuAI implementation, or the spec? I'm assuming the spec is based off of Risu, so I've been using that for testing.

(Edit: I checked and Risu won't load a png that uses `chara-ext-asset_:{path}`.)

**Comment by kwaroran** [comment]
`chara-ext-asset_:` is right. Risu currently has some implementation issues.

**Comment by DominaeDev** [comment]
Alright. Thanks for clarifying.
